#!/bin/sh

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

echo "Xft.dpi: 100" | xrdb -merge
# see: /usr/share/X11/xkb/symbols/de
setxkbmap 'de(us)'
flameshot &!

# to revert any mapping (only one mapping does not work) do:
# setxkbmap -option ''
setxkbmap -option caps:swapescape
xset r rate 200 50
xset -dpms

# disable screen saver / sleep / suspension
xset s off

#background image
#arcane src: https://www.reddit.com/r/arcane/comments/1gytwkn/s2_spoilers_arcane_final_wallpaper_release_act_3/#lightbox
~/.fehbg

xbindkeys
if [ ! "$(ps -e | grep 'i3status')" ]; then
  # redshift -l 49:11 -b 1:.3 &!
  exec i3
fi
